FROM nginx:1.12

#  default conf for proxy service
COPY ./default.conf /etc/nginx/conf.d/default.conf

# NOT FOUND response
COPY ./error.html /var/www/html/error.html

# Proxy configurations
COPY ./proxy.conf /etc/nginx/includes/
